"""
make_version_info.py - generates version_info.txt, the Windows version
resource PyInstaller embeds into TG3.exe. This is what fills in the
Properties > Details tab (File description, File version, Product name,
Product version, Copyright, ...) - right now none of that is set because
TG3.spec's EXE() call has no `version=` at all.

Run automatically by BUILD_TG3.bat, before PyInstaller, so
version_info.txt always matches version.py's VERSION - bump that one
number and the Details tab, window title, and About dialog all follow
without hand-editing a second file.
"""
import re
from version import VERSION

# Edit these three freely - they're static identity info for the exe, not
# really "version" info, so they don't come from version.py.
COMPANY_NAME     = 'TG3'
FILE_DESCRIPTION = 'Texture Generator 3 - batch texture/material/PBR tooling'
PRODUCT_NAME     = 'Texture Generator 3'
COPYRIGHT        = '\u00a9 2026'


def _version_tuple(v):
    """'1.1.6' -> (1, 1, 6, 0) - Windows version resources are always 4
    numbers, so a trailing 0 is padded on for a major.minor.patch string."""
    parts = [int(p) for p in re.findall(r'\d+', v)]
    while len(parts) < 4:
        parts.append(0)
    return tuple(parts[:4])


VTUP = _version_tuple(VERSION)
VSTR = '.'.join(str(n) for n in VTUP)

TEMPLATE = f'''# UTF-8
# Auto-generated by make_version_info.py from version.py - don't edit this
# file by hand. Edit version.py (for the version number) or the constants
# at the top of make_version_info.py (for name/description/copyright)
# instead, then re-run the build.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={VTUP},
    prodvers={VTUP},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName', u'{COMPANY_NAME}'),
        StringStruct(u'FileDescription', u'{FILE_DESCRIPTION}'),
        StringStruct(u'FileVersion', u'{VSTR}'),
        StringStruct(u'InternalName', u'TG3'),
        StringStruct(u'LegalCopyright', u'{COPYRIGHT}'),
        StringStruct(u'OriginalFilename', u'TG3.exe'),
        StringStruct(u'ProductName', u'{PRODUCT_NAME}'),
        StringStruct(u'ProductVersion', u'{VSTR}')])
      ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
'''

if __name__ == '__main__':
    with open('version_info.txt', 'w', encoding='utf-8') as f:
        f.write(TEMPLATE)
    print(f'version_info.txt written - v{VSTR}')
